// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAC7h6QZJg6LqbZ4ZqPBa64CGjCvg6vJX4',
    appId: '1:725971926828:web:7e4d324b7cab0e197a7689',
    messagingSenderId: '725971926828',
    projectId: 'fluttertp-8771e',
    authDomain: 'fluttertp-8771e.firebaseapp.com',
    storageBucket: 'fluttertp-8771e.firebasestorage.app',
    measurementId: 'G-TRN2F35RLX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBWY9nHTz0hSBGTeVkMfKyBy56P4KOURoM',
    appId: '1:725971926828:android:3e07d42f70e5ec817a7689',
    messagingSenderId: '725971926828',
    projectId: 'fluttertp-8771e',
    storageBucket: 'fluttertp-8771e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCqZ0p24YO2zdEe0vMlps-B8XFLpO-cyGg',
    appId: '1:725971926828:ios:088f42b57c2cc67e7a7689',
    messagingSenderId: '725971926828',
    projectId: 'fluttertp-8771e',
    storageBucket: 'fluttertp-8771e.firebasestorage.app',
    iosBundleId: 'com.example.tpflutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCqZ0p24YO2zdEe0vMlps-B8XFLpO-cyGg',
    appId: '1:725971926828:ios:088f42b57c2cc67e7a7689',
    messagingSenderId: '725971926828',
    projectId: 'fluttertp-8771e',
    storageBucket: 'fluttertp-8771e.firebasestorage.app',
    iosBundleId: 'com.example.tpflutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAC7h6QZJg6LqbZ4ZqPBa64CGjCvg6vJX4',
    appId: '1:725971926828:web:a0fdeb19f7dcc9ee7a7689',
    messagingSenderId: '725971926828',
    projectId: 'fluttertp-8771e',
    authDomain: 'fluttertp-8771e.firebaseapp.com',
    storageBucket: 'fluttertp-8771e.firebasestorage.app',
    measurementId: 'G-B63Y57W918',
  );
}
